name = "YARG"
home = "https://discord.com/channels/731205301247803413/1451771538943508490"
default_url = "https://github.com/energymaster22/YARGArchipelago/releases/download/{{version}}/yarg.apworld"

[versions]
"0.0.10" = {}
