name = "YAYARG"
home = "https://discord.com/channels/731205301247803413/1009608126321922180/threads/1469731900544258323"
default_url = "https://github.com/Thedrummonger/YargArchipelagoPluginV2/releases/tag/V2.4.0"

[versions]
"2.4.0" = {}
